# Generated by Django 5.1.7 on 2025-05-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_category_name_en_category_name_kk_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_escrow_funded',
            field=models.BooleanField(default=False, verbose_name='Is Escrow Funded'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
    ]
