# Generated by Django 5.1.7 on 2025-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_milestone_is_escrow_funded_milestone_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='is_escrow_funded',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='milestone',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid'), ('escrow', 'In Escrow')], default='not_paid', max_length=20, verbose_name='Payment Status'),
        ),
    ]
