# Generated by Django 5.1.7 on 2025-06-02 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_project_description_en_project_description_kk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('view_duration', models.PositiveIntegerField(default=0, verbose_name='View Duration (seconds)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project View',
                'verbose_name_plural': 'Project Views',
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
