# Generated by Django 5.1.7 on 2025-06-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_projectview'),
        ('payments', '0005_remove_transaction_milestone_delete_escrowpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
