services:
  - type: web
    name: workby
    env: python
    buildCommand: pip install -r requirements.txt && python freelance_platform/manage.py collectstatic --noinput
    startCommand: cd freelance_platform && gunicorn freelance_core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: PYTHON_VERSION
        value: 3.10.6
    healthCheckPath: /
