services:
  - type: web
    name: workby
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd freelance_platform && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn freelance_core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: true
      - key: RENDER
        value: true
      - key: SERVER_ENV
        value: render
      - key: USE_SQLITE
        value: true
      - key: PYTHON_VERSION
        value: 3.10.6
    healthCheckPath: /
