# Generated by Django 5.1.7 on 2025-06-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='milestone',
        ),
        migrations.DeleteModel(
            name='EscrowPayment',
        ),
    ]
