# Generated by Django 5.1.7 on 2025-06-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_milestone'),
        ('payments', '0005_remove_transaction_milestone_delete_escrowpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='jobs.milestone'),
        ),
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Escrow ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('funded_at', models.DateTimeField(blank=True, null=True, verbose_name='Funded At')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Released At')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Refunded At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_escrow_payments', to='payments.transaction')),
                ('freelancer_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_escrow_payments', to='payments.transaction')),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payment', to='jobs.milestone')),
            ],
            options={
                'verbose_name': 'Escrow Payment',
                'verbose_name_plural': 'Escrow Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
