from setuptools import setup, find_packages

setup(
    name="workby",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Django>=5.1.0,<5.2.0",
        "django-allauth>=0.60.0,<0.62.0",
        "django-crispy-forms>=2.0",
        "crispy-bootstrap4>=2022.1",
        "djangorestframework>=3.14.0",
        "django-filter>=23.0",
        "django-cors-headers>=4.0.0",
        "django-modeltranslation>=0.18.0",
        "django-debug-toolbar>=4.0.0",
        "Pillow>=10.0.0",
        "psycopg2-binary>=2.9.0",
        "stripe>=7.0.0",
        "channels>=4.0.0",
        "channels_redis>=4.1.0",
        "whitenoise>=6.5.0",
    ],
    description="Freelance marketplace platform",
    author="WorkBy Team",
    author_email="info@workby.com",
    keywords="freelance, marketplace, django",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Framework :: Django :: 5.1",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Topic :: Internet :: WWW/HTTP",
    ],
) 