# Generated by Django 5.1.7 on 2025-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_dark_mode_default_to_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark Mode'),
        ),
    ]
