# Generated by Django 5.1.7 on 2025-06-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_freelancerprofile_communication_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='City and country', max_length=255, verbose_name='Location'),
        ),
    ]
