# Generated by Django 5.1.7 on 2025-06-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('kk', 'Kazakh')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
