# Generated by Django 5.1.7 on 2025-05-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment'),
        ('jobs', '0005_remove_milestone_is_escrow_funded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='related_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='jobs.contract', verbose_name='Related Contract'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='jobs.project', verbose_name='Related Project'),
        ),
    ]
